name: Release application

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sb-jena
  IMAGE_TAG: 1.0

jobs:
  deploy:
    name: Publish to github registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'

      - id: repository_owner
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Build with Maven
        run: mvn install -U -P docker -Ddocker.repo=${{ env.REGISTRY }}/${{ steps.repository_owner.outputs.lowercase }} -Ddocker.app.tag=${{ env.IMAGE_TAG }}
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker image
        run: docker push -a ${{ env.REGISTRY }}/${{ steps.repository_owner.outputs.lowercase }}/${{ env.IMAGE_NAME }}
